InmobiliariaLorenzo/Models/Contrato.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace InmobiliariaLorenzo.Models;

public class Contrato
{
    [Key]
    [Display(Name = "N°")]
    public int Id_Contrato { get; set; }

    [Required, Display(Name = "Fecha de Inicio")]
    public DateTime Fecha_Inicio { get; set; }

    [Required, Display(Name = "Fecha de Finalización")]
    public DateTime Fecha_Fin { get; set; }

    [Required, Display(Name = "Monto Mensual")]
    public decimal Monto { get; set; }

    [Required, Display(Name = "Inmueble")]
    public int Id_Inmueble { get; set; }

    [ForeignKey(nameof(Id_Inmueble))]
    public Inmueble? Inmueble { get; set; }

    [Required, Display(Name = "Inquilino")]
    public int Id_Inquilino { get; set; }

    [ForeignKey(nameof(Id_Inquilino))]
    public Inquilino? Inquilino { get; set; }

    [Display(Name = "Creado por")]
    public int Id_Usuario_Creador { get; set; }

    [ForeignKey(nameof(Id_Usuario_Creador))]
    public Usuario? UsuarioCreador { get; set; }

    [Display(Name = "Finalizado por")]
    public int? Id_Usuario_Finalizador { get; set; }

    [ForeignKey(nameof(Id_Usuario_Finalizador))]
    public Usuario? UsuarioFinalizador { get; set; }
}

InmobiliariaLorenzo/Models/Pago.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace InmobiliariaLorenzo.Models;

public class Pago
{
    [Key]
    [Display(Name = "N°")]
    public int Id_Pago { get; set; } 

    [Required, Display(Name = "Fecha de Pago")]
    public DateTime Fecha { get; set; }


    [Required]
    public Decimal Importe { get; set; }


    [Required,Display(Name ="Contrato")]
    public int Id_Contrato{ get; set; }
    [ForeignKey(nameof(Id_Contrato))]
    public Contrato? Contrato { get; set; }

}

InmobiliariaLorenzo/Controllers/ContratosController.cs
using Microsoft.AspNetCore.Mvc;
using InmobiliariaLorenzo.Models;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;

namespace InmobiliariaLorenzo.Controllers
{
    [Authorize]
    public class ContratosController : Controller
    {
        private readonly IRepositorioContrato repoContrato;
        private readonly IRepositorioInmueble repoInmuble;
        private readonly IRepositorioInquilino repoInquilino;
        private readonly IConfiguration config;

        public ContratosController(IRepositorioContrato repo, IRepositorioInmueble repIn, IRepositorioInquilino repoInq, IConfiguration config)
        {
            this.repoContrato = repo;
            this.repoInmuble = repIn;
            this.repoInquilino = repoInq;
            this.config = config;
        }

        [Route("[controller]/Index")]
        public ActionResult Index()
        {
            var lista = repoContrato.ObtenerTodos();
            return View(lista);
        }

        public ActionResult Details(int id)
        {
            var contrato = repoContrato.ObtenerPorId(id);
            return View(contrato);
        }

        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.listaInmuebles = repoInmuble.ObtenerTodos();
            ViewBag.listaInquilinos = repoInquilino.ObtenerTodos();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Contrato contrato)
        {
            ViewBag.listaInmuebles = repoInmuble.ObtenerTodos();
            ViewBag.listaInquilinos = repoInquilino.ObtenerTodos();

            if (contrato.Fecha_Fin < contrato.Fecha_Inicio)
            {
                ModelState.AddModelError("Fecha_Fin", "La fecha de fin no puede ser anterior a la fecha de inicio.");
                return View(contrato);
            }

            var claim = User.FindFirst("Id") ?? User.FindFirst(ClaimTypes.NameIdentifier);
            if (claim == null)
            {
                TempData["Otro"] = "No se pudo identificar el usuario actual.";
                return RedirectToAction(nameof(Index));
            }

            contrato.Id_Usuario_Creador = int.Parse(claim.Value);

            if (repoInmuble.VerificarDisponibilidad(contrato.Id_Inmueble, contrato.Fecha_Inicio, contrato.Fecha_Fin))
            {
                repoContrato.Alta(contrato);
                TempData["creado"] = "Contrato Creado";
            }
            else
            {
                TempData["Otro"] = "No se pudo crear el contrato: no hay disponibilidad.";
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var contrato = repoContrato.ObtenerPorId(id);
            ViewBag.listaInmuebles = repoInmuble.ObtenerTodos();
            ViewBag.listaInquilinos = repoInquilino.ObtenerTodos();
            return View(contrato);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Contrato contrato)
        {
            ViewBag.listaInmuebles = repoInmuble.ObtenerTodos();
            ViewBag.listaInquilinos = repoInquilino.ObtenerTodos();

            if (contrato.Fecha_Fin < contrato.Fecha_Inicio)
            {
                ModelState.AddModelError("Fecha_Fin", "La fecha de fin no puede ser anterior a la fecha de inicio.");
                return View(contrato);
            }

            repoContrato.Modificacion(contrato);
            TempData["editado"] = "Contrato editado";
            return RedirectToAction(nameof(Index));
        }

        [Authorize(policy: "Administrador")]
        [HttpGet]
        public ActionResult Delete(int id)
        {
            var contrato = repoContrato.ObtenerPorId(id);
            return View(contrato);
        }

        [Authorize(policy: "Administrador")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Contrato contrato)
        {
            repoContrato.Baja(id);
            TempData["eliminado"] = "Contrato eliminado";
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public ActionResult ContratosPorInquilino(int id)
        {
            var lista = repoContrato.ObtenerContratosPorInquilino(id);
            return View(lista);
        }

        [HttpGet]
        public ActionResult FinalizarContrato(int id, int id_inquilino = 0)
        {
            var contrato = repoContrato.ObtenerPorId(id);
            ViewBag.id_inquilino = id_inquilino;
            ViewBag.Monto = repoContrato.CalcularMontoCancelacion(id);
            return View(contrato);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult FinalizarContrato(int id, Contrato contrato, int id_inquilino = 0)
        {
            ViewBag.id_inquilino = id_inquilino;
            var claim = User.FindFirst("Id") ?? User.FindFirst(ClaimTypes.NameIdentifier);
            int usuarioId = claim != null ? int.Parse(claim.Value) : 0;
            repoContrato.FinalizarContrato(id, usuarioId);
            TempData["Otro"] = "Contrato Finalizado Correctamente.";
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public ActionResult ContratosVigentes()
        {
            var lista = repoContrato.ObtenerContratosVigentes();
            return View(lista);
        }

        [HttpGet]
        public ActionResult ContratosInmuebles()
        {
            var lista = repoContrato.ObtenerTodos();
            ViewBag.listaInmuebles = repoInmuble.ObtenerTodos();
            return View(lista);
        }

        [HttpPost]
        public ActionResult ContratosInmuebles(ContratoBusqueda cb)
        {
            var lista = repoContrato.ObtenerContratosPorInmueble(cb);
            ViewBag.listaInmuebles = repoInmuble.ObtenerTodos();
            return View(lista);
        }

        [HttpGet]
        public ActionResult CreateContrato(int id_inmueble = 0)
        {
            ViewBag.id_inmueble = id_inmueble;
            ViewBag.listaInmuebles = repoInmuble.ObtenerTodos();
            ViewBag.listaInquilinos = repoInquilino.ObtenerTodos();
            return View("Create");
        }

        [HttpGet]
        public ActionResult RenovarContrato(int id_inmueble = 0, int id_inquilino = 0)
        {
            ViewBag.id_inmueble = id_inmueble;
            ViewBag.id_inquilino = id_inquilino;
            ViewBag.listaInmuebles = repoInmuble.ObtenerTodos();
            ViewBag.listaInquilinos = repoInquilino.ObtenerTodos();
            return View("Create");
        }
    }
}

InmobiliariaLorenzo/Controllers/PagosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using InmobiliariaLorenzo.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace InmobiliariaLorenzo.Controllers
{
   [Authorize]
    public class PagosController : Controller
    {
        private readonly IRepositorioPago repoPago;
        private readonly IConfiguration config;

        public PagosController(IRepositorioPago repo, IConfiguration config)
        {
            this.repoPago = repo;
            this.config = config;
        }

        // GET: Pagos
        [Route("[controller]/Index")]
        public ActionResult Index()
        {
            var Lista = repoPago.ObtenerTodos();
            return View(Lista);
        }

        // GET: Pagos/Details/5
        public ActionResult Details(int id)
        {
            var Lista = repoPago.ObtenerPorId(id);
            return View(Lista);
        }

        // GET: Pagos/Create

        public ActionResult Create()
        {
            return View();
        }

        // POST: Pagos/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Pago pago)
        {
            repoPago.Alta(pago);
            TempData["creado"] = "Si";
            return RedirectToAction(nameof(Index));
        }


        // GET: Pagos/Edit/5
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var Lista = repoPago.ObtenerPorId(id);
            return View(Lista);
        }

        // POST: Pagos/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Pago pago)
        {
            repoPago.Modificacion(pago);
            TempData["editado"] = "Si";
            return RedirectToAction(nameof(Index));
        }

        // GET: Pagos/Delete/5
        [Authorize(policy: "Administrador")]
        [HttpGet]
        public ActionResult Delete(int id)
        {
            var Lista = repoPago.ObtenerPorId(id);
            return View(Lista);
        }

        // POST: Pagos/Delete/5
        [Authorize(policy: "Administrador")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Pago pago)
        {          
            repoPago.Baja(id);
            TempData["eliminado"] = "Si";
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        // GET: Pagos/Create
        public ActionResult PagoPorContrato(int id, int id_inquilino = 0)
        {
            ViewBag.id_inquilino = id_inquilino;          
            ViewBag.Id_Contrato = id;
            ViewBag.ListaPagos = repoPago.PagosContratoPorInquilino(id);
            return View();
        }

        // POST: Pagos/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PagoPorContrato(int id, Pago pago)
        {           
            repoPago.Alta(pago);
            return RedirectToAction(nameof(PagoPorContrato), id);
        }
    }
}

InmobiliariaLorenzo/Views/Contratos/ContratosInmuebles.cshtml
@model IEnumerable<InmobiliariaLorenzo.Models.Contrato>

@{
    ViewData["Title"] = "Reporte de Contratos por Inmueble";
    var listaInmuebles = (List<InmobiliariaLorenzo.Models.Inmueble>)ViewBag.listaInmuebles;
}

<h2 class="mb-3">Reporte de Contratos por Inmueble</h2>
<p class="mb-4">Lista de todos los contratos registrados, filtrados por inmueble si se desea.</p>

<div class="card mb-4">
    <div class="card-header">Filtros</div>
    <div class="card-body">
        <form asp-action="ContratosInmuebles" method="get">
            <div class="row align-items-end">
                <div class="col-md-4">
                    <label for="Id_Inmueble" class="form-label">Inmueble</label>
                    <select id="Id_Inmueble" name="Id_Inmueble" class="form-select">
                        <option value="">Todos</option>
                        @foreach (var item in listaInmuebles)
                        {
                            <option value="@item.Id_Inmueble">@item.Direccion</option>
                        }
                    </select>
                </div>
                <div class="col-md-2">
                    <button type="submit" class="btn btn-primary mt-3">Filtrar</button>
                </div>
            </div>
        </form>
    </div>
</div>

<div class="card">
    <div class="card-header">Resultados</div>
    <div class="card-body">
        @if (!Model.Any())
        {
            <p class="text-muted">No se encontraron contratos para el inmueble seleccionado.</p>
        }
        else
        {
            <div class="table-responsive">
                <table class="table table-bordered table-hover align-middle">
                    <thead class="table-light">
                        <tr>
                            <th>@Html.DisplayNameFor(m => m.First().Id_Contrato)</th>
                            <th>@Html.DisplayNameFor(m => m.First().Fecha_Inicio)</th>
                            <th>@Html.DisplayNameFor(m => m.First().Fecha_Fin)</th>
                            <th>@Html.DisplayNameFor(m => m.First().Monto)</th>
                            <th>Inmueble</th>
                            <th>Inquilino</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.Id_Contrato</td>
                                <td>@item.Fecha_Inicio.ToShortDateString()</td>
                                <td>@item.Fecha_Fin.ToShortDateString()</td>
                                <td>$@item.Monto</td>
                                <td>@item.Inmueble.Direccion</td>
                                <td>@item.Inquilino.Nombre @item.Inquilino.Apellido</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        }
    </div>
</div>

InmobiliariaLorenzo/Views/Contratos/ContratosPorInquilino.cshtml
@model IEnumerable<InmobiliariaLorenzo.Models.Contrato>

@{
    ViewData["Title"] = "Contratos del Inquilino";
}

<h2 class="mb-3">Contratos del Inquilino</h2>

<p>
    <a asp-action="Create" class="btn btn-primary">Crear nuevo contrato</a>
</p>

<div class="card">
    <div class="card-header">
        Lista de contratos
    </div>
    <div class="card-body">
        @if (!Model.Any())
        {
            <p class="text-muted">Este inquilino no tiene contratos registrados.</p>
        }
        else
        {
            <div class="table-responsive">
                <table class="table table-bordered table-hover align-middle">
                    <thead class="table-light">
                        <tr>
                            <th>@Html.DisplayNameFor(model => model.First().Id_Contrato)</th>
                            <th>@Html.DisplayNameFor(model => model.First().Fecha_Inicio)</th>
                            <th>@Html.DisplayNameFor(model => model.First().Fecha_Fin)</th>
                            <th>@Html.DisplayNameFor(model => model.First().Monto)</th>
                            <th>Inmueble</th>
                            <th>Inquilino</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.Id_Contrato</td>
                                <td>@item.Fecha_Inicio.ToShortDateString()</td>
                                <td>@item.Fecha_Fin.ToShortDateString()</td>
                                <td>$@item.Monto</td>
                                <td>@item.Inmueble.Direccion</td>
                                <td>@item.Inquilino.Nombre @item.Inquilino.Apellido</td>
                                <td class="text-nowrap">
                                    <a asp-action="Edit" asp-route-id="@item.Id_Contrato" class="btn btn-warning btn-sm">Editar</a>
                                    <a asp-action="Details" asp-route-id="@item.Id_Contrato" class="btn btn-info btn-sm">Detalles</a>
                                    <a asp-action="Delete" asp-route-id="@item.Id_Contrato" class="btn btn-danger btn-sm">Eliminar</a>
                                    <a asp-controller="Pagos" asp-action="PagoPorContrato" asp-route-id="@item.Id_Contrato" asp-route-id_inquilino="@item.Inquilino.Id_Inquilino" class="btn btn-outline-primary btn-sm">Pagar</a>
                                    @if (DateTime.Now >= item.Fecha_Inicio && DateTime.Now <= item.Fecha_Fin)
                                    {
                                        <a asp-controller="Contratos" asp-action="FinalizarContrato" asp-route-id="@item.Id_Contrato" asp-route-id_inquilino="@item.Inquilino.Id_Inquilino" class="btn btn-outline-danger btn-sm">Finalizar</a>
                                    }
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        }
    </div>
</div>

InmobiliariaLorenzo/Views/Contratos/ContratosVigentes.cshtml
@model IEnumerable<InmobiliariaLorenzo.Models.Contrato>

@{
    ViewData["Title"] = "Reporte de Contratos Vigentes";
}

<h2 class="mb-3">Reporte de Contratos Vigentes</h2>
<p class="text-muted mb-4">Lista de todos los contratos de alquiler que se encuentren vigentes (por fecha de inicio y fin).</p>

<div class="card shadow-sm">
    <div class="card-header bg-primary text-white">
        <strong>Contratos Vigentes</strong>
    </div>
    <div class="card-body">
        @if (!Model.Any())
        {
            <div class="alert alert-info">
                No hay contratos vigentes en este momento.
            </div>
        }
        else
        {
            <div class="table-responsive">
                <table class="table table-striped table-hover align-middle">
                    <thead class="table-light">
                        <tr>
                            <th>ID</th>
                            <th>Inicio</th>
                            <th>Fin</th>
                            <th>Monto</th>
                            <th>Inmueble</th>
                            <th>Inquilino</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.Id_Contrato</td>
                                <td>@item.Fecha_Inicio.ToString("dd/MM/yyyy")</td>
                                <td>@item.Fecha_Fin.ToString("dd/MM/yyyy")</td>
                                <td>$@item.Monto</td>
                                <td>@item.Inmueble?.Direccion</td>
                                <td>@($"{item.Inquilino?.Nombre} {item.Inquilino?.Apellido}")</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        }
    </div>
</div>

InmobiliariaLorenzo/Views/Contratos/Crear.cshtml
@model InmobiliariaLorenzo.Models.Contrato

@{
    ViewData["Title"] = "Crear Contrato";
}

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" />

<h2 class="text-center my-4"><i class="bi bi-file-earmark-plus-fill"></i> Crear Contrato</h2>

<div class="card shadow-sm">
    <div class="card-body">
        <form asp-action="Crear">
            <div asp-validation-summary="ModelOnly" class="text-danger mb-3"></div>

            <div class="row">
                <div class="col-md-6 mb-3">
                    <label asp-for="InquilinoId" class="form-label">Inquilino</label>
                    <select asp-for="InquilinoId" class="form-select">
                        @foreach (var inquilino in ViewBag.ListaInquilinos)
                        {
                            <option value="@inquilino.Id">@inquilino.Nombre @inquilino.Apellido</option>
                        }
                    </select>
                    <span asp-validation-for="InquilinoId" class="text-danger"></span>
                </div>

                <div class="col-md-6 mb-3">
                    <label asp-for="InmuebleId" class="form-label">Inmueble</label>
                    <select asp-for="InmuebleId" class="form-select">
                        @foreach (var inmueble in ViewBag.ListaInmuebles)
                        {
                            <option value="@inmueble.Id">@inmueble.Direccion</option>
                        }
                    </select>
                    <span asp-validation-for="InmuebleId" class="text-danger"></span>
                </div>

                <div class="col-md-6 mb-3">
                    <label asp-for="FechaInicio" class="form-label">Fecha de Inicio</label>
                    <input type="date" asp-for="FechaInicio" class="form-control" />
                    <span asp-validation-for="FechaInicio" class="text-danger"></span>
                </div>

                <div class="col-md-6 mb-3">
                    <label asp-for="FechaFin" class="form-label">Fecha de Fin</label>
                    <input type="date" asp-for="FechaFin" class="form-control" />
                    <span asp-validation-for="FechaFin" class="text-danger"></span>
                </div>

                <div class="col-md-6 mb-3">
                    <label asp-for="Monto" class="form-label">Monto</label>
                    <input type="number" asp-for="Monto" class="form-control" />
                    <span asp-validation-for="Monto" class="text-danger"></span>
                </div>
            </div>

            <div class="text-end mt-4">
                <input type="submit" value="Crear" class="btn btn-primary" />
                <a asp-action="Index" class="btn btn-secondary ms-2">Volver a la lista</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

InmobiliariaLorenzo/Views/Contratos/FinalizarContrato.cshtml
@model InmobiliariaLorenzo.Models.Contrato

@{
    ViewData["Title"] = "Finalizar Contrato";
    var id_inquilino = (int)(ViewBag.id_inquilino != null ? ViewBag.id_inquilino : 0);
}

<h2 class="mb-3">Finalizar Contrato</h2>

<div class="card">
    <div class="card-header">
        Confirmación de finalización
    </div>
    <div class="card-body">
        <h5 class="text-danger">¿Estás seguro de que querés finalizar este contrato?</h5>
        <hr />

        <dl class="row">
            <dt class="col-sm-3">Contrato N°</dt>
            <dd class="col-sm-9">@Model.Id_Contrato</dd>

            <dt class="col-sm-3">Inicio</dt>
            <dd class="col-sm-9">@Model.Fecha_Inicio.ToShortDateString()</dd>

            <dt class="col-sm-3">Fin</dt>
            <dd class="col-sm-9">@Model.Fecha_Fin.ToShortDateString()</dd>

            <dt class="col-sm-3">Monto Mensual</dt>
            <dd class="col-sm-9">$@Model.Monto</dd>

            <dt class="col-sm-3">Inmueble</dt>
            <dd class="col-sm-9">@Model.Inmueble.Direccion</dd>

            <dt class="col-sm-3">Inquilino</dt>
            <dd class="col-sm-9">@Model.Inquilino.Nombre @Model.Inquilino.Apellido</dd>

            <dt class="col-sm-3">Monto de Cancelación</dt>
            <dd class="col-sm-9 text-danger fw-bold">$@ViewBag.Monto</dd>
        </dl>

        <form asp-action="FinalizarContrato" method="post">
            <input type="hidden" asp-for="Id_Contrato" />
            <button type="submit" class="btn btn-danger">Finalizar</button>

            @if (id_inquilino > 0)
            {
                <a asp-action="ContratosPorInquilino" asp-controller="Contratos" asp-route-id="@id_inquilino" class="btn btn-secondary ms-2">Volver al listado</a>
            }
            else
            {
                <a asp-action="Index" class="btn btn-secondary ms-2">Volver al listado</a>
            }
        </form>
    </div>
</div>

InmobiliariaLorenzo/Views/Contratos/Index.cshtml
@model IEnumerable<InmobiliariaLorenzo.Models.Contrato>

@{
    ViewData["Title"] = "Lista de Contratos";
}

<!-- Bootstrap Icons y FontAwesome -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" />
<script src="https://kit.fontawesome.com/708362d465.js" crossorigin="anonymous"></script>

<h2 class="mb-4"><i class="bi bi-file-earmark-text"></i> Lista de Contratos</h2>

<div class="mb-3">
    <a asp-action="Create" class="btn btn-success">
        <i class="fa-solid fa-plus"></i> Crear nuevo contrato
    </a>
</div>

<!-- Mensajes temporales -->
@foreach (var mensaje in new[] { "creado", "editado", "eliminado", "Otro" })
{
    if (TempData[mensaje] != null)
    {
        var clase = mensaje == "creado" ? "success"
                 : mensaje == "editado" ? "warning"
                 : "danger";
        <div class="alert alert-@clase" role="alert">
            @TempData[mensaje]
        </div>
    }
}

<!-- Tabla de contratos -->
<div class="card shadow-sm">
    <div class="card-body">
        <table class="table table-striped align-middle">
            <thead class="table-dark">
                <tr>
                    <th>@Html.DisplayNameFor(model => model.Id_Contrato)</th>
                    <th>@Html.DisplayNameFor(model => model.Fecha_Inicio)</th>
                    <th>@Html.DisplayNameFor(model => model.Fecha_Fin)</th>
                    <th>@Html.DisplayNameFor(model => model.Monto)</th>
                    <th>Inmueble</th>
                    <th>Inquilino</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Id_Contrato</td>
                        <td>@item.Fecha_Inicio.ToShortDateString()</td>
                        <td>@item.Fecha_Fin.ToShortDateString()</td>
                        <td>@item.Monto.ToString("C")</td>
                        <td>@item.Inmueble?.Direccion</td>
                        <td>@(item.Inquilino?.Nombre + " " + item.Inquilino?.Apellido)</td>
                        <td class="d-flex flex-wrap gap-2">
                            <a asp-action="Details" asp-route-id="@item.Id_Contrato" class="btn btn-sm btn-info" title="Detalles">
                                <i class="fa-solid fa-circle-info"></i>
                            </a>
                            <a asp-controller="Pagos" asp-action="PagoPorContrato" asp-route-id="@item.Id_Contrato" class="btn btn-sm btn-success" title="Pagar">
                                <i class="fas fa-dollar-sign"></i>
                            </a>
                            <a asp-action="Edit" asp-route-id="@item.Id_Contrato" class="btn btn-sm btn-warning" title="Editar">
                                <i class="fa-solid fa-pen-to-square"></i>
                            </a>
                            @if (User.IsInRole("Administrador"))
                            {
                                <a asp-action="Delete" asp-route-id="@item.Id_Contrato" class="btn btn-sm btn-danger" title="Eliminar">
                                    <i class="fa-solid fa-trash"></i>
                                </a>
                            }
                            @if (DateTime.Now >= item.Fecha_Inicio && DateTime.Now <= item.Fecha_Fin)
                            {
                                <a asp-action="FinalizarContrato" asp-route-id="@item.Id_Contrato" class="btn btn-sm btn-outline-danger" title="Finalizar">
                                    <i class="fa-solid fa-flag-checkered"></i>
                                </a>
                            }
                            @if (DateTime.Now < item.Fecha_Inicio || DateTime.Now > item.Fecha_Fin)
                            {
                                <a asp-action="RenovarContrato" asp-route-id_inquilino="@item.Id_Inquilino" asp-route-id_inmueble="@item.Id_Inmueble" class="btn btn-sm btn-outline-success" title="Renovar">
                                    <i class="fa-solid fa-rotate-right"></i>
                                </a>
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>